name: GitHub Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "the event that triggered the job is ${{ github.event_name}}"
          echo "the current branch is ${{ github.ref}} and the repo is ${{github.repository}}"
      
      - uses: actions/checkout@v3.3.0
      
      - name: List files in the repository
        run: |
          echo "The repository containes the following files"
          tree
    
  
  
