name: Reuse other workflow

on:
  workflow_dispatch:
    

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "Maxime"

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "The output is ${{ needs.call-workflow.outputs.current-time }}"
